// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: clinic.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClinicService_TriggerAnalysis_FullMethodName = "/clinic.ClinicService/TriggerAnalysis"
)

// ClinicServiceClient is the client API for ClinicService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClinicServiceClient interface {
	TriggerAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error)
}

type clinicServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClinicServiceClient(cc grpc.ClientConnInterface) ClinicServiceClient {
	return &clinicServiceClient{cc}
}

func (c *clinicServiceClient) TriggerAnalysis(ctx context.Context, in *AnalysisRequest, opts ...grpc.CallOption) (*AnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalysisResponse)
	err := c.cc.Invoke(ctx, ClinicService_TriggerAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClinicServiceServer is the server API for ClinicService service.
// All implementations must embed UnimplementedClinicServiceServer
// for forward compatibility.
type ClinicServiceServer interface {
	TriggerAnalysis(context.Context, *AnalysisRequest) (*AnalysisResponse, error)
	mustEmbedUnimplementedClinicServiceServer()
}

// UnimplementedClinicServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClinicServiceServer struct{}

func (UnimplementedClinicServiceServer) TriggerAnalysis(context.Context, *AnalysisRequest) (*AnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerAnalysis not implemented")
}
func (UnimplementedClinicServiceServer) mustEmbedUnimplementedClinicServiceServer() {}
func (UnimplementedClinicServiceServer) testEmbeddedByValue()                       {}

// UnsafeClinicServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClinicServiceServer will
// result in compilation errors.
type UnsafeClinicServiceServer interface {
	mustEmbedUnimplementedClinicServiceServer()
}

func RegisterClinicServiceServer(s grpc.ServiceRegistrar, srv ClinicServiceServer) {
	// If the following call panics, it indicates UnimplementedClinicServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClinicService_ServiceDesc, srv)
}

func _ClinicService_TriggerAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicServiceServer).TriggerAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicService_TriggerAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicServiceServer).TriggerAnalysis(ctx, req.(*AnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClinicService_ServiceDesc is the grpc.ServiceDesc for ClinicService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClinicService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clinic.ClinicService",
	HandlerType: (*ClinicServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerAnalysis",
			Handler:    _ClinicService_TriggerAnalysis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clinic.proto",
}
