// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: clinic.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalysisRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserInput         string                 `protobuf:"bytes,2,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	Title             string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PrimaryDiagnosis  string                 `protobuf:"bytes,4,opt,name=primary_diagnosis,json=primaryDiagnosis,proto3" json:"primary_diagnosis,omitempty"`
	AnamnesisItems    []string               `protobuf:"bytes,5,rep,name=anamnesis_items,json=anamnesisItems,proto3" json:"anamnesis_items,omitempty"`
	PhysicalExamItems []string               `protobuf:"bytes,6,rep,name=physical_exam_items,json=physicalExamItems,proto3" json:"physical_exam_items,omitempty"`
	ExpectedWorkup    []string               `protobuf:"bytes,7,rep,name=expected_workup,json=expectedWorkup,proto3" json:"expected_workup,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_clinic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_clinic_proto_rawDescGZIP(), []int{0}
}

func (x *AnalysisRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AnalysisRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *AnalysisRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnalysisRequest) GetPrimaryDiagnosis() string {
	if x != nil {
		return x.PrimaryDiagnosis
	}
	return ""
}

func (x *AnalysisRequest) GetAnamnesisItems() []string {
	if x != nil {
		return x.AnamnesisItems
	}
	return nil
}

func (x *AnalysisRequest) GetPhysicalExamItems() []string {
	if x != nil {
		return x.PhysicalExamItems
	}
	return nil
}

func (x *AnalysisRequest) GetExpectedWorkup() []string {
	if x != nil {
		return x.ExpectedWorkup
	}
	return nil
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_clinic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clinic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_clinic_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_clinic_proto protoreflect.FileDescriptor

const file_clinic_proto_rawDesc = "" +
	"\n" +
	"\fclinic.proto\x12\x06clinic\"\x94\x02\n" +
	"\x0fAnalysisRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x02 \x01(\tR\tuserInput\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12+\n" +
	"\x11primary_diagnosis\x18\x04 \x01(\tR\x10primaryDiagnosis\x12'\n" +
	"\x0fanamnesis_items\x18\x05 \x03(\tR\x0eanamnesisItems\x12.\n" +
	"\x13physical_exam_items\x18\x06 \x03(\tR\x11physicalExamItems\x12'\n" +
	"\x0fexpected_workup\x18\a \x03(\tR\x0eexpectedWorkup\"*\n" +
	"\x10AnalysisResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2U\n" +
	"\rClinicService\x12D\n" +
	"\x0fTriggerAnalysis\x12\x17.clinic.AnalysisRequest\x1a\x18.clinic.AnalysisResponseB\x0fZ\rclinithink/pbb\x06proto3"

var (
	file_clinic_proto_rawDescOnce sync.Once
	file_clinic_proto_rawDescData []byte
)

func file_clinic_proto_rawDescGZIP() []byte {
	file_clinic_proto_rawDescOnce.Do(func() {
		file_clinic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clinic_proto_rawDesc), len(file_clinic_proto_rawDesc)))
	})
	return file_clinic_proto_rawDescData
}

var file_clinic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clinic_proto_goTypes = []any{
	(*AnalysisRequest)(nil),  // 0: clinic.AnalysisRequest
	(*AnalysisResponse)(nil), // 1: clinic.AnalysisResponse
}
var file_clinic_proto_depIdxs = []int32{
	0, // 0: clinic.ClinicService.TriggerAnalysis:input_type -> clinic.AnalysisRequest
	1, // 1: clinic.ClinicService.TriggerAnalysis:output_type -> clinic.AnalysisResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clinic_proto_init() }
func file_clinic_proto_init() {
	if File_clinic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clinic_proto_rawDesc), len(file_clinic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clinic_proto_goTypes,
		DependencyIndexes: file_clinic_proto_depIdxs,
		MessageInfos:      file_clinic_proto_msgTypes,
	}.Build()
	File_clinic_proto = out.File
	file_clinic_proto_goTypes = nil
	file_clinic_proto_depIdxs = nil
}
